query GetIdentityRelations($identityId: String!) {
  getIdentityRelations(identityId: $identityId) {
    identityId
    platform {
      id
      identityId
      relation
    }
    tenants {
      id
      tenantId
      identityId
      relation
    }
    workspaces {
      id
      workspaceId
      identityId
      relation
    }
  }
}
