apiVersion: v1
kind: Secret
metadata:
  name: identity-pg-secret
type: Opaque
data:
  # Public use
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_DB: aXNzdWUtdHJhY2tlcg==
  POSTGRES_PASSWORD: c0dQWVJOeHFlcVVmNFpWZjFZMSVOY2R3Tlomajk5ITM=
