apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-pod
  ports:
    - port: 4000
      targetPort: {{ .Values.container.exposedPort }}
