apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: issue-tracker
build:
  artifacts:
    - image: sourabhrawatcc/activity
      context: .
      docker:
        dockerfile: Dockerfile
        target: activity

    - image: sourabhrawatcc/attachment
      context: .
      docker:
        dockerfile: Dockerfile
        target: attachment

    - image: sourabhrawatcc/email
      context: .
      docker:
        dockerfile: Dockerfile
        target: email

    - image: sourabhrawatcc/identity
      context: .
      docker:
        dockerfile: Dockerfile
        target: identity

    - image: sourabhrawatcc/issue-tracker
      context: .
      docker:
        dockerfile: Dockerfile
        target: issue-tracker

    - image: sourabhrawatcc/user
      context: .
      docker:
        dockerfile: Dockerfile
        target: user

  local:
    concurrency: 0
deploy:
  helm:
    releases:
      - name: activity
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/activity.values.yaml

      - name: attachment
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/attachment.values.yaml

      - name: email
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/email.values.yaml

      - name: identity
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/identity.values.yaml

      - name: issue-tracker
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/issue-tracker.values.yaml

      - name: user
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/user.values.yaml
