apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: issue-tracker
build:
  artifacts:
  - image: sourabhrawatcc/identity
    context: identity
    docker:
      dockerfile: Dockerfile
  - image: sourabhrawatcc/project
    context: project
    docker:
      dockerfile: Dockerfile
  - image: sourabhrawatcc/user
    context: user
    docker:
      dockerfile: Dockerfile
  - image: sourabhrawatcc/workspace
    context: workspace
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: identity
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/identity.values.yaml

    - name: project
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/project.values.yaml

    - name: user
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/user.values.yaml
      
    - name: workspace
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/workspace.values.yaml
