apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: issue-tracker
build:
  artifacts:
    - image: sourabhrawatcc/identity
      context: identity
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/identity/deployments/identity.deployment.yaml
    - k8s/identity/deployments/identity-postgres.deployment.yaml
