apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: issue-tracker
build:
  artifacts:
    - image: sourabhrawatcc/identity
      context: identity
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployments/dev/identity.depl.yaml
    - k8s/deployments/dev/identity-pg.depl.yaml
