apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: issue-tracker
build:
  artifacts:
  - image: sourabhrawatcc/activity
    context: servers/activity
    docker:
      dockerfile: Dockerfile
  - image: sourabhrawatcc/email
    context: servers/email
    docker:
      dockerfile: Dockerfile
  - image: sourabhrawatcc/identity
    context: servers/identity
    docker:
      dockerfile: Dockerfile
  - image: sourabhrawatcc/issue
    context: servers/issue
    docker:
      dockerfile: Dockerfile
  - image: sourabhrawatcc/project
    context: servers/project
    docker:
      dockerfile: Dockerfile
  - image: sourabhrawatcc/user
    context: servers/user
    docker:
      dockerfile: Dockerfile
  - image: sourabhrawatcc/workspace
    context: servers/workspace
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: activity
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/activity.values.yaml

    - name: email
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/email.values.yaml

    - name: identity
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/identity.values.yaml

    - name: issue
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/issue.values.yaml

    - name: project
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/project.values.yaml

    - name: user
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/user.values.yaml
      
    - name: workspace
      chartPath: ./k8s/microservice
      valuesFiles:
      - ./k8s/microservice/workspace.values.yaml
