apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: issue-tracker
build:
  artifacts:
    - image: sourabhrawatcc/identity
      context: identity
      docker:
        dockerfile: Dockerfile
    - image: sourabhrawatcc/user
      context: user
      docker:
        dockerfile: Dockerfile
    - image: sourabhrawatcc/workspace
      context: workspace
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployments/identity-postgres.deployment.yaml
    - k8s/deployments/identity.deployment.yaml

    - k8s/deployments/user-postgres.deployment.yaml
    - k8s/deployments/user.deployment.yaml

    - k8s/deployments/workspace.deployment.yaml
    - k8s/deployments/workspace-postgres.deployment.yaml
