apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: issue-tracker-services
build:
  artifacts:
    - image: sourabhrawatcc/attachment
      context: .
      docker:
        dockerfile: Dockerfile
        target: attachment

    - image: sourabhrawatcc/email
      context: .
      docker:
        dockerfile: Dockerfile
        target: email

    - image: sourabhrawatcc/auth
      context: .
      docker:
        dockerfile: Dockerfile
        target: auth

    - image: sourabhrawatcc/issue-tracker
      context: .
      docker:
        dockerfile: Dockerfile
        target: issue-tracker

  local:
    concurrency: 0
deploy:
  helm:
    releases:
      - name: attachment
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/attachment.values.yaml

      - name: email
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/email.values.yaml

      - name: auth
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/auth.values.yaml

      - name: issue-tracker
        chartPath: ./k8s/microservice
        valuesFiles:
          - ./k8s/microservice/issue-tracker.values.yaml
