apiVersion: v1
kind: Secret
metadata:
  name: identity-postgres-secret
type: Opaque
data:
  POSTGRES_DB: aXNzdWUtdHJhY2tlcg==
  POSTGRES_PASSWORD: c0dQWVJOeHFlcVVmNFpWZjFZMSVOY2R3Tlomajk5ITM=
