apiVersion: v1
kind: PersistentVolume
metadata:
  name: identity-postgres-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/host/c/data/identity-postgres"
