apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-postgres-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/run/desktop/mnt/host/c/data/user-postgres"
