apiVersion: v1
kind: PersistentVolume
metadata:
  name: identity-postgres-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: "/run/desktop/mnt/host/c/data/identity-postgres"
