openapi: 3.0.0
info:
  title: Issue Tracker API
  version: 1.0.0
  description: API for describing various endpoints of issue tracker
  license:
    name: ISC
    url: https://github.com/sourabh-singh-rawat/issue-tracker/blob/master/LICENSE

servers:
  - url: http://localhost:4000/api

tags:
  - name: identity
    description: Authentication and user management service.

paths:
  # identity
  /identity/signup:
    $ref: ./paths/identity/signup.yaml
  /identity/login:
    $ref: ./paths/identity/login.yaml
  /identity/logout:
    $ref: ./paths/identity/logout.yaml
  /identity/refresh:
    $ref: ./paths/identity/refresh.yaml
  # /identity/password-reset:
  #   $ref: ./paths/identity/password-reset.yaml
  # /identity/verify-email:
  #   $ref: ./paths/identity/verify-email.yaml
  # user profile get and post

security: []

components:
  responses:
    InternalServerError:
      $ref: ./components/responses/InternalServerError.yaml

  schemas:
    Email:
      $ref: ./components/schema/Email.yaml
    Error:
      $ref: ./components/schema/Error.yaml
