openapi: 3.0.0
info:
  title: Issue Tracker API
  version: 1.0.0
  description: API for describing various endpoints of issue tracker
  license:
    name: ISC
    url: https://github.com/sourabh-singh-rawat/issue-tracker/blob/master/LICENSE

servers:
  - url: http://localhost:80/api/v1

tags:
  - name: identity
    description: Authentication and authorization functionalities.
  - name: user
    description: User management
  - name: workspace
    description: Create and manage workspaces

paths:
  /users/register:
    description: Create or register a new user
    $ref: user/paths/register.yaml
  /users/verify-password:
    description: Verifies user password
    $ref: user/paths/verify-password.yaml
  /users/me:
    description: Gets the current logged in user
    $ref: user/paths/me.yaml
  /users/default-workspace:
    description: Gets the current logged in user
    $ref: user/paths/default-workspace.yaml
  /identity/generate-tokens:
    description: Generate access and refresh tokens
    $ref: identity/paths/generate-tokens.yaml
  /identity/refresh-tokens:
    description: If refresh token is valid, generate new access and refresh tokens
    $ref: identity/paths/refresh-tokens.yaml
  /workspaces:
    description: Create and get workspaces
    $ref: workspace/paths/workspaces.yaml
  /workspaces/{id}:
    description: Create and get workspaces
    $ref: workspace/paths/workspace.yaml
  /projects:
    description: Create and get projects
    $ref: project/paths/projects.yaml
  /projects/status:
    description: Get a list of project statues
    $ref: project/paths/status.yaml

security: []
