openapi: 3.0.0
info:
  title: Issue Tracker API
  version: 1.0.0
  description: API for describing various endpoints of issue tracker
  license:
    name: ISC
    url: https://github.com/sourabh-singh-rawat/issue-tracker/blob/master/LICENSE

servers:
  - url: http://localhost:80/api/v1

tags:
  - name: identity
    description: Authentication and user management service.

paths:
  /identity/signup:
    description: Create a user
    $ref: identity/paths/signup.path.yaml
  /identity/login:
    description: Login a user
    $ref: identity/paths/login.path.yaml
  /identity/users/me:
    description: Gets the current logged in user
    $ref: identity/paths/me.path.yaml
  # /identity/users/{id}/email:
  #   $ref: ./identity/paths/users-email.path.yaml
  # /identity/users/{id}/password:

  # /identity/login:
  #   $ref: ./paths/identity/login.yaml

  # /identity/logout:
  #   $ref: ./paths/identity/logout.yaml

  # /identity/refresh:
  #   $ref: ./paths/identity/refresh.yaml
  # # /identity/password-reset:
  #   $ref: ./paths/identity/password-reset.yaml
  # /identity/verify-email:
  #   $ref: ./paths/identity/verify-email.yaml
  # user profile get and post

security: []
