openapi: 3.0.0
info:
  title: Issue Tracker API
  version: 1.0.0
  description: API for describing various endpoints of issue tracker
  license:
    name: ISC
    url: https://github.com/sourabh-singh-rawat/issue-tracker/blob/master/LICENSE

servers:
  - url: http://localhost:80/api/v1

tags:
  - name: identity
    description: Authentication functionalities.
  - name: issue
    description: Create and manage issues  
  - name: project
    description: Create and manage projects
  - name: user
    description: User management
  - name: workspace
    description: Create and manage workspaces

paths:
  /identity/generate-tokens:
    description: Generate access and refresh tokens
    $ref: identity/paths/generate-tokens.yaml
  /identity/refresh-tokens:
    description: If refresh token is valid, generate new access and refresh tokens
    $ref: identity/paths/refresh-tokens.yaml
  /issues:
    description: Create and get issues
    $ref: issue/paths/issues.yaml
  /issues/{id}:
    description: Get or update a issue
    $ref: issue/paths/issue.yaml  
  /issues/{id}/comments:
    description: Get comments or create a new comment
    $ref: issue/paths/comments.yaml
  /issues/status:
    description: Get a list of issue statuses
    $ref: issue/paths/status.yaml
  /issues/priority:
    description: Get a list of issue priorities
    $ref: issue/paths/priority.yaml
  /projects:
    description: Create and get projects
    $ref: project/paths/projects.yaml
  /projects/status:
    description: Get a list of project statuses
    $ref: project/paths/status.yaml
  /projects/{id}:
    description: Update the project status
    $ref: project/paths/project.yaml
  /projects/{id}/members:
    description: Get project members
    $ref: project/paths/members.yaml
  /users/register:
    description: Create or register a new user
    $ref: user/paths/register.yaml
  /users/verify-password:
    description: Verifies user password
    $ref: user/paths/verify-password.yaml
  /users/me:
    description: Gets the current logged in user
    $ref: user/paths/me.yaml
  /users/default-workspace:
    description: Gets the current logged in user
    $ref: user/paths/default-workspace.yaml
  /workspaces:
    description: Create and get workspaces
    $ref: workspace/paths/workspaces.yaml
  /workspaces/{id}:
    description: Create and get workspaces
    $ref: workspace/paths/workspace.yaml
security: []
