openapi: 3.1.0
info:
  title: Issue Tracker API
  version: 1.0.0
  description: API for describing various endpoints of issue tracker
  license:
    name: ISC
    url: https://github.com/sourabh-singh-rawat/issue-tracker/blob/master/LICENSE

servers:
  - url: https://localhost:443/api/v1

tags:
  - name: activity
    description: Activity service
  - name: identity
    description: Authentication functionalities.
  - name: issue
    description: Create and manage issues
  - name: project
    description: Create and manage projects
  - name: user
    description: User management
  - name: workspace
    description: Create and manage workspaces

paths:
  /issue-tracker/activities/projects/{id}:
    description: Get project activity list
    $ref: activity/paths/projects.yaml
  /attachments/issues/{id}:
    description: Create and manage issue attachments
    $ref: attachment/paths/attachments.yaml
  /auth/identity/generate-tokens:
    description: Generate access and refresh tokens
    $ref: identity/paths/generate-tokens.yaml
  /auth/identity/refresh-tokens:
    description: If refresh token is valid, generate new access and refresh tokens
    $ref: identity/paths/refresh-tokens.yaml
  /auth/identity/revoke-tokens:
    description: Revokes the token from cookie and database
    $ref: identity/paths/revoke-tokens.yaml
  /issue-tracker/issues:
    description: Create and get issues
    $ref: issue/paths/issues.yaml
  /issue-tracker/issues/status:
    description: Get a list of issue statuses
    $ref: issue/paths/status.yaml
  /issue-tracker/issues/priority:
    description: Get a list of issue priorities
    $ref: issue/paths/priority.yaml
  /issue-tracker/issues/{id}:
    description: Get or update a issue
    $ref: issue/paths/issue.yaml
  /issue-tracker/issues/{id}/status:
    description: Get or update an issue status
    $ref: issue/paths/issue-status.yaml
  /issue-tracker/issues/{id}/resolution:
    description: Get or update an issue resolution
    $ref: issue/paths/issue-resolution.yaml
  /issue-tracker/issues/{id}/comments:
    description: Get comments or create a new comment
    $ref: issue/paths/comments.yaml
  /issue-tracker/issues/{id}/comments/{commentId}:
    description: Delete a comment
    $ref: issue/paths/comment.yaml
  /issue-tracker/issues/{id}/tasks:
    description: Create and gets issue tasks
    $ref: issue/paths/tasks.yaml
  /issue-tracker/issues/{id}/tasks/{taskId}:
    description: Get or update a issue task
    $ref: issue/paths/task.yaml
  # /issues/{id}/assignees:
  # description: Add new assignees or remove existing assignees
  /issue-tracker/projects:
    description: Create and get projects
    $ref: project/paths/projects.yaml
  /issue-tracker/projects/status:
    description: Get a list of project statuses
    $ref: project/paths/status.yaml
  /issue-tracker/projects/{id}:
    description: Update the project status
    $ref: project/paths/project.yaml
  /issue-tracker/projects/{id}/role:
    description: Get project roles
    $ref: project/paths/role.yaml
  /issue-tracker/projects/{id}/members:
    description: Get project members
    $ref: project/paths/members.yaml
  /issue-tracker/projects/{id}/members/invite:
    description: Invite project member
    $ref: project/paths/invite.yaml
  /issue-tracker/projects/{id}/workspace-members:
    description: Get workspace members
    $ref: project/paths/workspace-member.yaml
  /auth/users/register:
    description: Create or register a new user
    $ref: user/paths/register.yaml
  /auth/users/verify-password:
    description: Verifies user password
    $ref: user/paths/verify-password.yaml
  /auth/users/me:
    description: Gets the current logged in user
    $ref: user/paths/me.yaml
  /auth/users/default-workspace:
    description: Gets the current logged in user
    $ref: user/paths/default-workspace.yaml
  /issue-tracker/workspaces:
    description: Create and get workspaces
    $ref: workspace/paths/workspaces.yaml
  /issue-tracker/workspaces/{id}:
    description: Get workspace
    $ref: workspace/paths/workspace.yaml
  /issue-tracker/workspaces/invite:
    description: Creates a workspace member
    $ref: workspace/paths/invite.yaml
  /issue-tracker/workspaces/{id}/members:
    description: Get all workspace members
    $ref: workspace/paths/workspace-members.yaml
  /issue-tracker/workspaces/role:
    description: Get a list of workspace roles
    $ref: workspace/paths/role.yaml
security: []
