query GetMyWorkspaces {
  getMyWorkspaces {
    id
    tenantId
    parentWorkspaceId
    name
    slug
    description
    isActive
    createdAt
    children {
      id
      tenantId
      parentWorkspaceId
      name
      slug
      description
      isActive
      createdAt
      children {
        id
        tenantId
        parentWorkspaceId
        name
        slug
        description
        isActive
        createdAt
        children {
          id
          tenantId
          parentWorkspaceId
          name
          slug
          description
          isActive
          createdAt
          children {
            id
            tenantId
            parentWorkspaceId
            name
            slug
            description
            isActive
            createdAt
            children {
              id
              tenantId
              parentWorkspaceId
              name
              slug
              description
              isActive
              createdAt
            }
          }
        }
      }
    }
  }
}
