/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AuthenticatedRouteImport } from './../routes/_authenticated'
import { Route as CallbackRouteImport } from './../routes/callback'
import { Route as AuthenticatedIndexRouteImport } from './../routes/_authenticated/index'
import { Route as AuthenticatedIdentitiesRouteImport } from './../routes/_authenticated/identities'
import { Route as AuthenticatedTenantsRouteImport } from './../routes/_authenticated/tenants'
import { Route as AuthenticatedIdentitiesIdentityIdRouteImport } from './../routes/_authenticated/identities_.$identityId'
import { Route as AuthenticatedRolesRoleIdRouteImport } from './../routes/_authenticated/roles_.$roleId'
import { Route as AuthenticatedTenantsTenantIdRouteImport } from './../routes/_authenticated/tenants_.$tenantId'
import { Route as AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRouteImport } from './../routes/_authenticated/tenants_.$tenantId_.workspaces.$workspaceId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdentitiesRoute = AuthenticatedIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdentitiesIdentityIdRoute =
  AuthenticatedIdentitiesIdentityIdRouteImport.update({
    id: '/identities_/$identityId',
    path: '/identities/$identityId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesRoleIdRoute =
  AuthenticatedRolesRoleIdRouteImport.update({
    id: '/roles_/$roleId',
    path: '/roles/$roleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdRoute =
  AuthenticatedTenantsTenantIdRouteImport.update({
    id: '/tenants_/$tenantId',
    path: '/tenants/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRoute =
  AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/tenants_/$tenantId_/workspaces/$workspaceId',
    path: '/tenants/$tenantId/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/identities': typeof AuthenticatedIdentitiesRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/identities/$identityId': typeof AuthenticatedIdentitiesIdentityIdRoute
  '/roles/$roleId': typeof AuthenticatedRolesRoleIdRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/tenants/$tenantId/workspaces/$workspaceId': typeof AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/identities': typeof AuthenticatedIdentitiesRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/': typeof AuthenticatedIndexRoute
  '/identities/$identityId': typeof AuthenticatedIdentitiesIdentityIdRoute
  '/roles/$roleId': typeof AuthenticatedRolesRoleIdRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/tenants/$tenantId/workspaces/$workspaceId': typeof AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/identities': typeof AuthenticatedIdentitiesRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/identities_/$identityId': typeof AuthenticatedIdentitiesIdentityIdRoute
  '/_authenticated/roles_/$roleId': typeof AuthenticatedRolesRoleIdRoute
  '/_authenticated/tenants_/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/_authenticated/tenants_/$tenantId_/workspaces/$workspaceId': typeof AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/identities'
    | '/tenants'
    | '/identities/$identityId'
    | '/roles/$roleId'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/workspaces/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/identities'
    | '/tenants'
    | '/'
    | '/identities/$identityId'
    | '/roles/$roleId'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/identities'
    | '/_authenticated/tenants'
    | '/_authenticated/'
    | '/_authenticated/identities_/$identityId'
    | '/_authenticated/roles_/$roleId'
    | '/_authenticated/tenants_/$tenantId'
    | '/_authenticated/tenants_/$tenantId_/workspaces/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/identities': {
      id: '/_authenticated/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof AuthenticatedIdentitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/identities_/$identityId': {
      id: '/_authenticated/identities_/$identityId'
      path: '/identities/$identityId'
      fullPath: '/identities/$identityId'
      preLoaderRoute: typeof AuthenticatedIdentitiesIdentityIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles_/$roleId': {
      id: '/_authenticated/roles_/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof AuthenticatedRolesRoleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants_/$tenantId': {
      id: '/_authenticated/tenants_/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants_/$tenantId_/workspaces/$workspaceId': {
      id: '/_authenticated/tenants_/$tenantId_/workspaces/$workspaceId'
      path: '/tenants/$tenantId/workspaces/$workspaceId'
      fullPath: '/tenants/$tenantId/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIdentitiesRoute: typeof AuthenticatedIdentitiesRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedIdentitiesIdentityIdRoute: typeof AuthenticatedIdentitiesIdentityIdRoute
  AuthenticatedRolesRoleIdRoute: typeof AuthenticatedRolesRoleIdRoute
  AuthenticatedTenantsTenantIdRoute: typeof AuthenticatedTenantsTenantIdRoute
  AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRoute: typeof AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIdentitiesRoute: AuthenticatedIdentitiesRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedIdentitiesIdentityIdRoute:
    AuthenticatedIdentitiesIdentityIdRoute,
  AuthenticatedRolesRoleIdRoute: AuthenticatedRolesRoleIdRoute,
  AuthenticatedTenantsTenantIdRoute: AuthenticatedTenantsTenantIdRoute,
  AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRoute:
    AuthenticatedTenantsTenantIdWorkspacesWorkspaceIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
