apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: {{ .Values.pvSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
