apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: sourabhrawatcc/identity
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - name: identity-port
              containerPort: 4000
          envFrom:
            - secretRef:
                name: identity-pg-secret
            - secretRef:
                name: github-token-secret
