apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-postgres
  template:
    metadata:
      labels:
        app: identity-postgres
    spec:
      containers:
        - name: identity-postgres
          image: postgres:15.3-alpine3.18
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: identity-postgres-secret
