apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-pod
  template:
    metadata:
      labels:
        app: identity-pod
    spec:
      containers:
        - name: identity-container
          image: sourabhrawatcc/identity
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - name: identity
              containerPort: 4000
          envFrom:
            - secretRef:
                name: identity-postgres-secret
