apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: {{ .Values.name }}-project
spec:
  streamName: {{ .Values.stream }}
  durableName: {{ .Values.name }}-project
  deliverPolicy: all
  filterSubject: {{ .Values.subject }}
  maxDeliver: 20
  ackWait: 30s
  ackPolicy: explicit
  replayPolicy: instant
