apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: {{ .Values.streamName }}-stream
spec:
  name: {{ .Values.streamName }}
  description: stream to store messages on {{ .Values.streamName  }}.*
  subjects:
    - "{{ .Values.streamName }}.*"
  storage: file
