apiVersion: v1
kind: PersistentVolume
metadata:
  name: identity-pg-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: "/g/data/identity-pg"
