apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: user-created-consumer
spec:
  streamName: user
  durableName: user-created-consumer
  deliverPolicy: all
  filterSubject: user.created
  maxDeliver: 20
  ackPolicy: explicit
  replayPolicy: instant
