apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-postgres-volume-claim
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
